[package]
name = "test-assembly"
version = "0.1.0"
edition.workspace = true
publish = false
repository.workspace = true
license = "Zlib OR Apache-2.0 OR MIT"

build = "build.rs"

[lints]
workspace = true

[dependencies]
cargo_metadata = "0.18"
rustc-demangle = "0.1"
regex = "1.6"
lazy_static = "1.4.0"
