[package]
name = "test_ns_string"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
icrate = { path = "../../../icrate", default-features = false }

[features]
default = ["apple", "std", "Foundation", "Foundation_NSString"]
std = ["icrate/std"]

# Runtime
apple = ["icrate/apple"]
gnustep-1-7 = ["icrate/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "icrate/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "icrate/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "icrate/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "icrate/gnustep-2-1"]

Foundation = ["icrate/Foundation"]
Foundation_NSString = ["icrate/Foundation_NSString"]

# Hack
assembly-features = ["Foundation", "Foundation_NSString", "icrate/unstable-static-nsstring"]
