[package]
name = "test_fast_enumeration"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
objc2 = { path = "../../../objc2", default-features = false, optional = true }
icrate = { path = "../../../icrate", default-features = false, optional = true }

[features]
default = ["apple", "std", "icrate", "objc2", "Foundation", "Foundation_NSArray"]
std = ["icrate?/std"]

# Runtime
apple = ["icrate?/apple"]
gnustep-1-7 = ["icrate?/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "icrate?/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "icrate?/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "icrate?/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "icrate?/gnustep-2-1"]

Foundation = ["icrate/Foundation"]
Foundation_NSArray = ["icrate/Foundation_NSArray"]

# Hack
assembly-features = ["Foundation", "Foundation_NSArray", "objc2"] # "objc2?/unstable-static-sel-inlined"
