[package]
name = "objc2-proc-macros"
# Remember to update html_root_url in lib.rs
version = "0.1.1"
description = "Procedural macros for the objc2 project"
keywords = ["objective-c", "macos", "ios", "proc-macro"]
categories = [
    "development-tools",
    "os::macos-apis",
]
authors = ["Mads Marquart <mads@marquart.dk>", "Calvin Watford"]
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[features]
default = ["apple"]

# Runtime selection (for future compatibility)
apple = []
gnustep-1-7 = []
gnustep-1-8 = ["gnustep-1-7"]
gnustep-1-9 = ["gnustep-1-8"]
gnustep-2-0 = ["gnustep-1-9"]
gnustep-2-1 = ["gnustep-2-0"]

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
