[package]
name = "objc2-encode"
# Remember to update html_root_url in lib.rs
version = "4.0.0"
description = "Objective-C type-encoding representation and parsing"
keywords = ["objective-c", "macos", "ios", "encode"]
categories = [
    "development-tools::ffi",
    "encoding",
    "no-std",
    "os::macos-apis",
]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["std"]

std = ["alloc"]
# Currently not possible to turn off, put here for forwards compatibility
alloc = []

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"

targets = [
    # MacOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    # "i686-apple-darwin",
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    # "i386-apple-ios",
    # GNUStep
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
]
